global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "default-receiver"
  routes:
    - group_by: ["nodejs_process_up"]
      receiver: "dingtalk"
      match:
        severity: info

    - group_by: ["nodejs_process_down"]
      receiver: "dingtalk"
      match:
        severity: fatal

    - group_by: ["request_qps"]
      group_wait: 10s
      group_interval: 10s
      receiver: "dingtalk"
      match:
        severity: waring

receivers:
  - name: "default-receiver"

  - name: "dingtalk"
    webhook_configs:
      - url: "http://dingtalk:8060/dingtalk/webhook2/send"
        send_resolved: false

  - name: "dingtalk_fatal"
    webhook_configs:
      - url: "http://dingtalk:8060/dingtalk/webhook_mention_users/send"
        send_resolved: false

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
  # - source_match:
  #     severity: "info"
  #   target_match:
  #     severity: "info"
  #   equal: ["alertname", "team"]
