global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "default-receiver"
  routes:
    - group_by: ["nodejs_process_up"]
      group_wait: 1m
      receiver: "dingtalk"
      match:
        severity: info

    - group_by: ["nodejs_process_down"]
      group_wait: 10s
      receiver: "dingtalk_fatal"
      match:
        severity: fatal

receivers:
  - name: "default-receiver"

  - name: "dingtalk"
    webhook_configs:
      - url: "http://dingtalk:8060/dingtalk/webhook2/send"

  - name: "dingtalk_fatal"
    webhook_configs:
      - url: "http://dingtalk:8060/dingtalk/webhook_mention_users/send"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
