global:
  scrape_interval: 10s # 抓取的频率
  scrape_timeout: 10s
  evaluation_interval: 40s # 表达式的计算频率

rule_files:
  - /etc/prometheus/rules/*.rules

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "dingtalk"
    static_configs:
      - targets: ["dingtalk:8060"]

  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "my-app"
    metrics_path: "/my-metric"
    file_sd_configs:
      - files: ["/prometheus/targets.json"]
        refresh_interval: 20s
